# Aliases
alias filemanager='pcmanfm'
alias zshconfig='vim ~/.zshrc'
alias vimrc='vim ~/.vimrc'
alias git='nocorrect git'
alias environment='sudo vim /etc/environment'
alias sudo='sudo -E '
alias dev='cd ~/Development'
alias notebook='jupyter notebook'
alias clipboard='xsel -b'
alias ll='ls -l'
# git-explorer from https://github.com/alexrochas/git-explorer
alias lg='git-explorer explore --light'
alias docker-rm-images='docker rmi $(docker images -q)'
alias docker-rm-containers='docker rm $(docker ps -a -q)'
alias docker-build-up='docker-compose build && docker-compose up'
alias search-txt='function _search(){find ./ -type f -exec grep --color=always -Hil "$1" {} \;};_search'
alias easy-vim='vim -y'
alias doh='TF_CMD=$(TF_ALIAS=fuck PYTHONIOENCODING=utf-8 TF_SHELL_ALIASES=$(alias) thefuck $(fc -ln -1 | tail -n 1)) && eval $TF_CMD && print -s $TF_CMD'
alias portainer='docker run -d -p 9000:9000 -v "/var/run/docker.sock=:/var/run/docker.sock" portainer/portainer'
alias abnt='setxkbmap -model abnt2 -layout br -variant abnt2'
alias infinite='function _while(){while true; do eval "$1"; done;};_while'
alias volume='pavucontrol'
alias fuse-log='function _parseLog(){ zcat $1 | sed -r "s/.*line\":(.*),\"host.*/\1/" | bunyan; };_parseLog'
alias docker-fuse-log='while read line; do echo $line | sed -r "s/^.*\|.*(\{.*)$/\1/" | bunyan; done;'
alias pdf='mupdf'
alias vpn='(echo -e "Agco@2017" & cat) | sudo openconnect savpn.agcocorp.com -u "sa\as70469" --passwd-on-stdin'
alias test-mic='arecord | aplay'
alias git-iamright='function iamright(){ git pull -Xtheirs --rebase; };iamright'
alias git-youright='function youright(){ git pull -Xtheirs; };youright'
alias git-rm-all='git status -s | cut -c4- | xargs rm'
