# Aliases
alias filemanager='pcmanfm'
alias zshconfig='vim ~/.zshrc'
alias vimrc='vim ~/.vimrc'
alias git='nocorrect git'
alias environment='sudo vim /etc/environment'
alias sudo='sudo -E '
alias dev='cd ~/Development'
alias notebook='jupyter notebook'
alias clipboard='xsel -b'
alias ll='ls -l'
# git-explorer from https://github.com/alexrochas/git-explorer
alias lg='git-explorer explore --light'
alias docker-rm-images='docker rmi $(docker images -q)'
alias docker-rm-containers='docker rm $(docker ps -a -q)'
alias docker-build-up='docker-compose build && docker-compose up'
alias docker-local-up='docker-compose -f ./docker-compose-local.yml up'
alias docker-node-run-scenario='function _run(){docker-compose build; docker-compose run --rm web bash -c "npm run dbTasks && npm run configMq && npm run cucumberTest $1";};_run'
alias search-txt='function _search(){find ./ -type f -exec grep --color=always -Hil "$1" {} \;};_search'
alias easy-vim='vim -y'
alias doh='TF_CMD=$(TF_ALIAS=fuck PYTHONIOENCODING=utf-8 TF_SHELL_ALIASES=$(alias) thefuck $(fc -ln -1 | tail -n 1)) && eval $TF_CMD && print -s $TF_CMD'
alias portainer='docker run -d -p 9000:9000 -v "/var/run/docker.sock=:/var/run/docker.sock" portainer/portainer'
alias abnt='setxkbmap -model abnt2 -layout br -variant abnt2'
alias infinite='function _while(){while true; do eval "$1"; done;};_while'
alias volume='pavucontrol'
alias fuse-log='function _parseLog(){ zcat $1 | sed -r "s/.*line\":(.*),\"host.*/\1/" | bunyan; };_parseLog'
alias docker-fuse-log='while read line; do echo $line | sed -r "s/^.*\|.*(\{.*)$/\1/" | bunyan; done;'
alias pdf='mupdf'
#alias vpn='echo -e "123S0ch1n" | sudo openconnect navpn.agcocorp.com -u "rochaal" --passwd-on-stdin < /dev/tty'
alias run-vpn="ssh_decrypt agco | sudo openconnect savpn.agcocorp.com -u "mandiahy" --passwd-on-stdin </dev/tty"
alias test-mic='arecord | aplay'
alias git-iamright='function iamright(){ git pull -Xtheirs --rebase; };iamright'
alias git-youright='function youright(){ git pull -Xtheirs; };youright'
alias git-rm-all='git status -s | cut -c4- | xargs rm'
alias battery-status='upower -i $(upower -e | grep 'BAT') | grep -E "state|to\ full|percentage"'
alias be='bundle exec'
alias jekyll-start='bundle exec jekyll serve'
alias jekyll-start-draft='bundle exec jekyll serve --draft'
alias edit-alias='vim ~/.zsh/aliases.zsh'
alias docker-stop-containers='docker stop $(docker ps -a -q)'
alias reboot-wifi="sudo service network-manager restart"
alias jupyter-lab="nvm use v6.11.0; jupyter-lab"
alias how="tldr"
alias elastic='docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.1.3'
alias wifi-config='kde5-nm-connection-editor'
alias which-port='function _whichPort() { lsof -i tcp:$1; }; _whichPort'
alias jaxb='echo "--add-modules java.xml.bind"'
alias git-next='git reset HEAD@{1}'
alias start-swagger='docker run -p 80:8080 swaggerapi/swagger-editor'
alias origin='function _origin() { dpkg -S $(which $1); }; _origin'
alias net-manager='nmtui'
alias docker-stop-all='docker stop $(docker ps -aq)'
alias minkube-stop='systemctl stop localkube'
alias docker-prune='docker network prune'
alias install='sudo apt install'
alias mem='free -h'
alias disk='df -h'
alias lc='colorls -lA --sd'
